### ISSUE TITLE
added another level

### ISSUE THREAD

**Issue by starlightknown** [kaiwalyakoparkar/sense-hacker#28]
found a password guesser game which can be used as level 2, it's in html,css,js. easy to implement. we can show the importance of strong passwords, we can added the same hacker character in here too 

here is the game [LINK](https://codepen.io/CoryMaklin/pen/OZqRoq)

**Comment by kaiwalyakoparkar** [comment]
Thats a great Idea !

**Comment by starlightknown** [comment]
Can we add it please ? It just needs a simple redirect , the whole code is there
