### ISSUE TITLE
Create assets folder to organize files 

### ISSUE THREAD

**Issue by vinzvinci** [kaiwalyakoparkar/sense-hacker#49]
Things to add it in **assets folder**:

- assets > **css**
- assets > **js**
- assets > **img**
- assets > **icon-fonts**

**Comment by vinzvinci** [comment]
Huh? there's no feature label when I created **Feature request** issue, something bug now?

**Comment by kaiwalyakoparkar** [comment]
Might be. Would you like to go ahead and solve this issue. Should I assign this to you?

**Comment by vinzvinci** [comment]
Yeah I'll take this issue

**Comment by kaiwalyakoparkar** [comment]
Thank you , I have assigned this to you!

**Comment by vinzvinci** [comment]
I think someone may take this issue if it's still not done. Got a full schedule. sorry, looking forward to teaming up again for the hackathon.

**Comment by kaiwalyakoparkar** [comment]
@vinzvinci Yeah! I am a bit of busy as well. Will make it soon !!

**Comment by mohit200008** [comment]
can i work on this ?

**Comment by kaiwalyakoparkar** [comment]
@mohit200008 Sure! Feel free to ask for any help! :) Should I assign this to you?

**Comment by mohit200008** [comment]
just put the files in the assets folder ?
and changing the imports?

**Comment by kaiwalyakoparkar** [comment]
Yup Put all the folders (CSS, js, img, fonts) into the assets folder and change the links respectively!

**Comment by mohit200008** [comment]
can you check i made a pr?

**Comment by kaiwalyakoparkar** [comment]
> can you check i made a pr?

Thanks for your contribution. It's merged now :)
