### ISSUE TITLE
Typo in description

### ISSUE THREAD

**Issue by starlightknown** [kaiwalyakoparkar/sense-hacker#52]
![Screenshot_2021-04-12-19-33-24-141_com android chrome](https://user-images.githubusercontent.com/74637789/114407452-071b6d80-9bc6-11eb-9343-5fc02e708d92.jpg)
Correct the spelling from `price` to `prize`

**Comment by kaiwalyakoparkar** [comment]
Done! Thanks for the report :+1:

**Comment by starlightknown** [comment]
I still don't see the changes tho

**Comment by kaiwalyakoparkar** [comment]
I think my internet died while doing it and did not actually update it. Now it's done!
