### ISSUE TITLE
Hide Wiki

### ISSUE THREAD

**Issue by vinzvinci** [kaiwalyakoparkar/sense-hacker#56]
Hide Wiki since it wasn't use

**Comment by kaiwalyakoparkar** [comment]
Hey @vinzvinci Can you provide steps to hide them?

**Comment by vinzvinci** [comment]
Go to the settings of this repository. Then scroll down and you'll see Wiki there, just uncheck it.

**Comment by kaiwalyakoparkar** [comment]
Thank you @vinzvinci I have done that now :)
