### ISSUE TITLE
Hide Packages

### ISSUE THREAD

**Issue by verma-kunal** [kaiwalyakoparkar/sense-hacker#57]
Suggested to hide packages if not being used !!

**Comment by kaiwalyakoparkar** [comment]
Thanks for the suggestion @verma-kunal :smile: I appreciate that

**Comment by kaiwalyakoparkar** [comment]
Hey @verma-kunal, Can you provide steps for doing that. I don't really have an idea how to do that :sweat:

**Comment by verma-kunal** [comment]
Yeah sure !! Head over to the **About section settings** in your repo and uncheck the **packages** there !

![Screenshot 2021-05-22 at 12 49 17 AM](https://user-images.githubusercontent.com/72245772/119187881-8b032800-ba97-11eb-9275-722cecaaa177.png)

**Comment by kaiwalyakoparkar** [comment]
@verma-kunal Thanks for the help I have removed the packages section. I am closing this issue. If you want then you can raise more issues! :)
